### ISSUE TITLE
Hide open/close curtains during every page refresh

### ISSUE THREAD

**Issue by viveikt** [AndreaLombardo/BootSideMenu#11]
Hello, 

First of all this is a wonderful menu slider. Loved every bit of it. But I am stuck in a small problem. 

```
if(autoClose){
  $(this).find(".toggler").trigger("click");
}
```

I have implemented the BootSideMenu in my application but on every page refresh or moving on to a new page the slider curtains pop out and go back in. I would like the it to stay in the same place and not animate. 

Can you please help me to achieve this. Thanks in advance.

**Comment by viveikt** [comment]
Can any of you guys please help me regarding this. I am stuck on this issue for a long time.

**Comment by AndreaLombardo** [comment]
Hi @viveikt  this project is incomplete and no longer maintained, I'm working on a new version but I'm very busy on my job. Hoping the new version can include your request.
Thanks for your interesting

**Comment by AndreaLombardo** [comment]
Hi @viveikt 
thanks for your interest.
Yes it is fixed. You can see it here https://andrealombardo.github.io/BootSideMenu/examples/11-remote-control.html
