### ISSUE TITLE
Does Bootsidemenu support submenu?

### ISSUE THREAD

**Issue by supercreator** [AndreaLombardo/BootSideMenu#12]
This plugin is cool. User interface is simple and flexible. Are there these feature in this plugin? 
- Multi-level submenu (already found it, Nice!)
- Auto push body content when use large screen and push body content off when use small screen
- Assign arrow position from top, the arrow position always slightly move in mobile device when scrolling up and down, it's better if there is option to solve this problem
- The method to show, hide or toggle menu, that can be called from button or link 
  (  already found the method  https://github.com/AndreaLombardo/BootSideMenu/issues/9 )

Thank you BootSideMenu

**Comment by AndreaLombardo** [comment]
Hi @supercreator , thanks for your comments.
About your second point, if you set the option pushBody to true it will be ignored by default on small screen.
Maybe in the future there will be something like what you are asking for in the 3rd point.

Have a nice day
