### ISSUE TITLE
Use on multiple page site

### ISSUE THREAD

**Issue by squirc77** [AndreaLombardo/BootSideMenu#15]
Hi,
I really like this BootSideMenu, it's one of the best I've seen. It does everything I'd like it to except that it's built for a one page site. I'm trying to use it on a multi-page site with the correct <a> tags staying selected but not getting it. Been trying to add show/hide active class which it will work correctly after I'm on the page and click another link. I'd like the correct <a> tag to be selected when I navigate to its respective page.  Could you please help by providing some code to guide me along?

Regards.

**Comment by AndreaLombardo** [comment]
Hi, thanks for your attention.
The way is to give an id for each menu's items. When user click on it a function store the item's id into a cookie before navigate to other page.
On startup another function checks for the existence of that cookie, pick the id and use it to find the item to change 'active' class.
Maybe in the future (I'have a lot of work for now) I'll be able to add this feature to the plugin.
Regards.

**Comment by squirc77** [comment]
Thanks so much! 

    On Wednesday, June 7, 2017 1:51 AM, Andrea <notifications@github.com> wrote:
 

 Hi, thanks for your attention.
The way is to give an id for each menu's items. When user click on it a function store the item's id into a cookie before navigate to other page.
On startup another function checks for the existence of that cookie, pick the id and use it to find the item to change 'active' class.
Maybe in the future (I'have a lot of work for now) I'll be able to add this feature to the plugin.
Regards.—

**Comment by bobbyben** [comment]
would be nice to be integrated

**Comment by AndreaLombardo** [comment]
Hope ASAP ;-)
