### ISSUE TITLE
Chosen Drop down not working

### ISSUE THREAD

**Issue by anandbohra** [AndreaLombardo/BootSideMenu#17]
Hi,
I have downloaded your code & it worked perfect & all my filter condition are now on sidemenu.
but i observed that my Chosen Dropdown & chosed listbox does not work under sidemenu.

can you please guide me what is fix for that.

**Comment by AndreaLombardo** [comment]
Hi,
can you show me your code please?

Andrea


Il 23 ago 2017 9:49 AM, "anandbohra" <notifications@github.com> ha scritto:

**Comment by anandbohra** [comment]
html
```

<div id="MySideMenu">
 <div class="col-lg-12 col-md-6 col-sm-6">
                <div class="form-group label-floating">

                    @Html.DropDownList("sortOrder", new List<SelectListItem>()
    {
        new SelectListItem(){Text="Price High to Low", Value="MRPDesc"},
        new SelectListItem(){Text="Price Low to High", Value="MRP"},
        new SelectListItem(){Text="Gross Wt High to Low", Value="GrossWTDesc"},
        new SelectListItem(){Text="Gross Wt Low to High", Value="GrossWT"}

    }, "Select Sorting", new { style = "width: 210px;", @Class = "chosen-select" })
                </div>
            </div>
</div>


```




Jquery
 $('.chosen-select').chosen(
       {
           search_contains: true
       }

);


            $('#MySideMenu').BootSideMenu({
                side: "left"
                , width: '25%'
                , pushBody: false
                , remember: false
                , autoClose: true                           


            });

**Comment by AndreaLombardo** [comment]
Hi, this plugin expects dom element written in the format like the one shown here:
http://www.lombardoandrea.com/demo/BootSideMenu/examples/0-menu-template.html

I don't know what is
 ` 
@Html.DropDownList("sortOrder", new List<SelectListItem>()
...
...
"Select Sorting", new { style = "width: 210px;", @Class = "chosen-select" })
` 
If this is a backend code, please show me what is the output viewed by the browser.

**Comment by anandbohra** [comment]
@html.dropdownlist is Razor syntax to generate Drop down box

below is generated html code

```
<select class="chosen-select" data-val="true" data-val-number="The field Diam Quality must be a number." data-val-required="Diam Quality ID is must" id="DiamQualityID" name="DiamQualityID"><option value="">Select Diam Quality</option>
<option value="1">SIGHI</option>
<option value="2">I1GHI</option>
<option value="3">SIJK</option>
<option value="4">VSGHI</option>
<option value="5">VVSGHI</option>
<option value="6">VVSDEF</option>
</select>
```

basically chosen doesn't work if it is placed inside sidemenu

**Comment by AndreaLombardo** [comment]
Hi @anandbohra , sorry for the super late reply.
I tried to add a selectbox like yours under the user's pic section and it seems to be working fine.
See if it can be done for you.

Sorry again for the late asnware
