### ISSUE TITLE
Other Icons for Toggler?

### ISSUE THREAD

**Issue by SchweizerSchoggi** [AndreaLombardo/BootSideMenu#18]
Hi, 
I really love this slide menu, but I have one issue:
I already use FontAwesome in my current project and I don't wanna add a second font language.
In your sample you are using glyphicon for the icons - and there seems to be no way to change these, is this right?

**Comment by AndreaLombardo** [comment]
Hi, it's correct sorry...
If you want modify it by yourself, simply edit the js file and find and replace my glyphicon with your fontawesome.
Maybe in the future this will be a customizable option, but for now I have not enough time to spend on it, sorry.

**Comment by AndreaLombardo** [comment]
Hi @SchweizerSchoggi , 
I spent some time for you ;-)
https://andrealombardo.github.io/BootSideMenu/examples/9-change-arrows-font.html

**Comment by SchweizerSchoggi** [comment]
Awesome, thank you Andrea!! Thats a much cleaner solution now, makes even
more fun to use!!

I bought you a Coffee for this! :-X

Am 17.12.2017 7:10 nachm. schrieb "Andrea" <notifications@github.com>:

**Comment by AndreaLombardo** [comment]
You are welcome @SchweizerSchoggi and thanks for your Coffee ;-)
