### ISSUE TITLE
I did update your awesome work to a bower component

### ISSUE THREAD

**Issue by aoopvn** [AndreaLombardo/BootSideMenu#2]
Hi Andrea Lombardo,
Thank you very much for your awesome work.
I did fork your work then update it for easy to reuse with bower. 
Thanks to that, and here [the repository result](https://github.com/aoopvn/jquery.sliding.menu)
I keep it with an MIT license and absolutely you're the author.
Thanks and happy coding!

**Comment by AndreaLombardo** [comment]
Thanks aoopvn! Good job!
