### ISSUE TITLE
Auto close when you click outside the menu

### ISSUE THREAD

**Issue by viveikt** [AndreaLombardo/BootSideMenu#21]
Hi Andrea,

Wonderful update loved every bit of it. 

Just wanted to know if it is possible to click outside the menu slider which would auto close the menu? 

Regards,
Vivek

**Comment by AndreaLombardo** [comment]
Hi @viveikt 
Give a try using a test-and-improvements branch.
Let me know if it works fine.

**Comment by viveikt** [comment]
Thank you so much Andrea. Works like a charm. Appreciate your help.

**Comment by AndreaLombardo** [comment]
You are welcome @viveikt
I appreciated your coffee ;-)

Thanks
