### ISSUE TITLE
Is this issue fixed in this new version?

### ISSUE THREAD

**Issue by viveikt** [AndreaLombardo/BootSideMenu#27]
Hi Andrea,

Hello once again. I am just wondering if [this](https://github.com/AndreaLombardo/BootSideMenu/issues/11) feature which I had written long back has been fixed in the new version ?

**Comment by AndreaLombardo** [comment]
Hi @viveikt 
thanks for your interest.
Yes it is fixed. You can see it here https://andrealombardo.github.io/BootSideMenu/examples/11-remote-control.html
