### ISSUE TITLE
Content Overlay?

### ISSUE THREAD

**Issue by SchweizerSchoggi** [AndreaLombardo/BootSideMenu#29]
Hi Andrea
Is there any possibility to have a (dark) content overlay while showing the BootSideMenu?

Greetings!
Bianca

**Comment by AndreaLombardo** [comment]
Hi Bianca,
what do you mean with content overlay?
Something to partially obscure the rest of the page?

**Comment by SchweizerSchoggi** [comment]
Exactly!
A (gray) Overlay as we use for modal dialogs

Am 04.01.2018 2:20 nachm. schrieb "Andrea" <notifications@github.com>:

**Comment by AndreaLombardo** [comment]
Not too bad idea, maybe I can add this feature in a future release :-D
