### ISSUE TITLE
Menu is open when loading the page first time

### ISSUE THREAD

**Issue by viveikt** [AndreaLombardo/BootSideMenu#30]
Hi Andrea,

Hope you are doing good. 

The menu slider is open the first time I open the the menu and later it stays closed. But I would like it to be closed initially too. How is it possible to achieve this. I am not really good at JavaScript so need your help. 

Thank you very much.

**Comment by AndreaLombardo** [comment]
Hi @viveikt 
have you tried to use autoClose:true into declaration options ;-)
