### ISSUE TITLE
Question about width of the Sidebar

### ISSUE THREAD

**Issue by StefanGIT** [AndreaLombardo/BootSideMenu#5]
Dear Andrea,
i would like to use your BootSideMenu, since it exactly fits what i need. However i was not able to control the width of the expanded sidebar. In you test.html this is nicely set to approx 1/4th of the screen. In my case, the expanded sidebar always goes over 2/3 of the screen. I would need exactly 1/2 of the screen. How can i control the width of the sidebar?

**Comment by AndreaLombardo** [comment]
Hi @StefanGIT, sorry for my delay, but I was not in place.
So the BootSideMenu was only a test and as you probably noticed it's no longer maintained. 
Sorry for that, but actually i'm working to another project and have no time to spend on it.
