### ISSUE TITLE
BootSideMenu is not working with angularjs

### ISSUE THREAD

**Issue by satishsahani33** [AndreaLombardo/BootSideMenu#7]
When i use angularjs controller inside bootsidemenu div then it is not working.
I want to load content for bootsidemenu from angularjs controller.
It is not recognising any angularjs code, and when i look into console of browser the angular code is commented. Can anyone please provide me a solution?
![bootsidemenu](https://cloud.githubusercontent.com/assets/4965226/15847297/763012de-2ca4-11e6-8e94-90ec6417bf18.JPG)

**Comment by AndreaLombardo** [comment]
Hi, try to use the new version of the code and check if it works. Try to call plugin after your content was loaded. Anyway, my knowledge in angularjs is very poor and I'm not able to help you.
