### ISSUE TITLE
Toggle sidebar via separate link?

### ISSUE THREAD

**Issue by harrisdavidharris** [AndreaLombardo/BootSideMenu#9]
Quick question: is there a way to toggle the sidebar (or just open it) via a separate link on the page?  I'm trying to include an icon that will open it that is grouped with other icons, for users who may not notice the toggle on the side.

**Comment by AndreaLombardo** [comment]
Hi,
try this: 
`$('#your-sidebar-id').find(".toggler").trigger("click");`

**Comment by harrisdavidharris** [comment]
Thank you! Hope this is useful to others as well.

**Comment by AndreaLombardo** [comment]
I'll try to implement something such 
`$('#your-sidebar-id').BootSideMenu("close");` 
and
` $('#your-sidebar-id').BootSideMenu("open");`
